### 登陆接口测试
GET http://127.0.0.1:8080/user/login
Content-Type: application/json

{
  "userName": "admin",
  "userPassword": "admin"
}

### 注册接口测试
POST http://127.0.0.1:8080/user/register
Content-Type: application/json

{
  "userName": "admin1",
  "userPassword": "admin",
  "userEmail": "admin@admin.com",
  "userRole": "USER",
  "userStatus": 0
}

### 获取所有车辆
GET http://127.0.0.1:8080/car
